version: 2
jobs:
  py3.7: &py
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: pip install -e '.[tests]'
      - run: pytest
  py3.8:
    <<: *py
    docker:
      - image: python:3.8
  py3.9:
    <<: *py
    docker:
      - image: python:3.9
  py3.10:
    <<: *py
    docker:
      - image: python:3.10
  py3.11:
    <<: *py
    docker:
      - image: python:3.11
  py3.12:
    <<: *py
    docker:
      - image: python:3.12
  py3.13:
    <<: *py
    docker:
      - image: python:3.13

workflows:
  version: 2
  all:
    jobs:
      - py3.7
      - py3.8
      - py3.9
      - py3.10
      - py3.11
      - py3.12
      - py3.13
